"""empty message

Revision ID: 315a356cd2cc
Revises: e20164bcc24e
Create Date: 2018-10-03 19:14:30.826404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315a356cd2cc'
down_revision = 'e20164bcc24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_last_seen', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_last_seen', 'user', ['last_seen'], unique=False)
    # ### end Alembic commands ###
